export const STARTER_RECIPES = [
  {
    id: 100001,
    name: 'Aftermath by Flawless',
    flavors: [
      { name: 'Berry (Crunch) Cereal (TPA)', value: 1 },
      { name: 'Blueberry Extra (TPA)', value: 6 },
      { name: 'Glazed Doughnut (CAP)', value: 3.5 },
      { name: 'Sweetener (Sucralose) (TPA)', value: 2 },
      { name: 'Vanilla Bean Ice Cream (FW)', value: 3 },
    ],
    createdAt: '2026-02-11T00:00:00.000Z',
    source: 'craftvaping.com - Aftermath by Flawless',
  },
  {
    id: 100002,
    name: 'Afternoon Delight (Honey Pearry style)',
    flavors: [
      { name: 'Pear (TPA)', value: 6 },
      { name: 'Honeydew (TPA)', value: 6 },
      { name: 'Strawberry (TPA)', value: 3 },
    ],
    createdAt: '2026-01-27T00:00:00.000Z',
    source: '99juices.com - recipe 1762',
  },
  {
    id: 100003,
    name: 'Apple Buttah',
    flavors: [
      { name: 'Fuji Apple (FA)', value: 4 },
      { name: 'Liquid Amber (FA)', value: 0.5 },
      { name: 'Butter Cream (CAP)', value: 2 },
      { name: 'Cinnamon Danish Swirl V1 (CAP)', value: 0.5 },
      { name: 'Vanilla Custard V1 (CAP)', value: 1 },
      { name: 'Vanilla Bean Ice Cream (TPA)', value: 1 },
    ],
    createdAt: '2026-02-09T00:00:00.000Z',
    source: 'craftvaping.com - Apple Buttah (goldfish18)',
  },
  {
    id: 100004,
    name: 'Arnies Horchata',
    flavors: [
      { name: 'Horchata Smooth (TPA)', value: 5 },
      { name: 'Malted Milk Conc (TPA)', value: 2 },
      { name: 'Cinnamon Spice (TPA)', value: 1.5 },
      { name: 'Toasted Almond (TPA)', value: 1.5 },
      { name: 'Vanilla Swirl (TPA)', value: 2 },
      { name: 'Sweetener (TPA)', value: 3 },
    ],
    createdAt: '2026-02-06T00:00:00.000Z',
    source: '99juices.com - recipe 304',
  },
  {
    id: 100005,
    name: 'Banana Nut Bread',
    flavors: [
      { name: 'Banana Nut Bread (TPA)', value: 11 },
      { name: 'French Vanilla (TPA)', value: 2 },
      { name: 'Cinnamon (TPA)', value: 2 },
      { name: 'Brown Sugar (TPA)', value: 3 },
    ],
    createdAt: '2026-02-06T00:00:00.000Z',
    source: '99juices.com - recipe 566',
  },
  {
    id: 100006,
    name: 'Bananadoodles',
    flavors: [
      { name: 'Sugar Cookie (CAP)', value: 4.5 },
      { name: 'Super Sweet (CAP)', value: 0.25 },
      { name: 'Rich Cinnamon (FLV)', value: 0.05 },
      { name: 'Banana Cream (TPA)', value: 2.5 },
      { name: 'Cinnamon Sugar Cookie (TPA)', value: 1.5 },
    ],
    createdAt: '2026-02-06T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 32040',
  },
  {
    id: 100007,
    name: 'Basic Loops - Straight up Fruit Loops',
    flavors: [
      { name: 'Cereal 27 (CAP)', value: 2.5 },
      { name: 'Fruit Circles (CAP)', value: 6 },
      { name: 'Sweetener (TPA)', value: 1.5 },
    ],
    createdAt: '2026-01-29T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 98832',
  },
  {
    id: 100008,
    name: 'Bavarian Double RY4 10 VG',
    flavors: [
      { name: 'Caramel Candy (TPA)', value: 5 },
      { name: 'RY4 Double (TPA)', value: 10 },
      { name: 'Bavarian Cream Vanilla (LA)', value: 5 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: '99juices.com - recipe 1474',
  },
  {
    id: 100009,
    name: 'Beard No. 32 Clone - Cinnamon Funnel Cake',
    flavors: [
      { name: 'DX Bavarian Cream (TPA)', value: 5 },
      { name: 'Butter Pecan (FW)', value: 3 },
      { name: 'Cinnamon Danish Swirl (CAP)', value: 2 },
      { name: 'Brown Sugar (TPA)', value: 2 },
      { name: 'Joy (FA)', value: 1 },
      { name: 'Banana Nut Bread (TPA)', value: 0.6 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: '99juices.com - recipe 4294',
  },
  {
    id: 100010,
    name: 'Beard No.71 Clone',
    flavors: [
      { name: 'Yellow Peach (CAP)', value: 4 },
      { name: 'Sweet Tangerine (CAP)', value: 1 },
      { name: 'Sour (TPA)', value: 1.5 },
      { name: 'Marshmallow (CAP)', value: 0.5 },
      { name: 'Sweet Cream (CAP)', value: 1.5 },
      { name: 'Peach with Stevia (CAP)', value: 1 },
      { name: 'Super Sweet (CAP)', value: 0.5 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 3929',
  },
  {
    id: 100011,
    name: 'Beard Vape Co. No. 5 Clone',
    flavors: [
      { name: 'Cheesecake Graham Crust (TPA)', value: 2 },
      { name: 'New York Cheesecake v2 (CAP)', value: 4 },
      { name: 'Malted Milk (OOO)', value: 5 },
      { name: 'Sweet Strawberry (CAP)', value: 12 },
      { name: 'Vanilla Custard (TPA)', value: 6 },
      { name: 'Graham Cracker Clear (TPA)', value: 2 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: '99juices.com - recipe 9690',
  },
  {
    id: 100012,
    name: 'Better Than Mothers Milk',
    flavors: [
      { name: 'Super Sweet (CAP)', value: 0.5 },
      { name: 'Sweet Strawberry (CAP)', value: 5 },
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 4.5 },
      { name: 'Strawberry (Ripe) (TPA)', value: 3 },
      { name: 'Vanilla Bean Ice Cream (TPA)', value: 2 },
    ],
    createdAt: '2026-02-02T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 66563',
  },
  {
    id: 100013,
    name: 'Black tea latte',
    flavors: [
      { name: 'Bavarian Cream (CAP)', value: 1.1 },
      { name: 'Black Tea (FW)', value: 5 },
      { name: 'Chocolate (TPA)', value: 1.4 },
      { name: 'Dx Sweet Cream (TPA)', value: 3 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 62011',
  },
  {
    id: 100014,
    name: 'Blueberry Cotton Candy',
    flavors: [
      { name: 'Cotton Candy (TPA)', value: 15 },
      { name: 'Blueberry (CAP)', value: 5 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 221',
  },
  {
    id: 100015,
    name: 'Blueberry Muffin - Signature E-juice by TBD Liquids',
    flavors: [
      { name: 'Blueberry (wild) (TPA)', value: 10 },
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 5 },
      { name: 'Cotton Candy (TPA)', value: 1.75 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: 'alltheflavors.com - TBD Liquids',
  },
  {
    id: 100016,
    name: 'Boba Thai Chai Tea',
    flavors: [
      { name: 'Cream (FLV)', value: 0.6 },
      { name: 'Starch Base (FLV)', value: 0.2 },
      { name: 'Thai Chai (FLV)', value: 0.6 },
      { name: 'Toffee (FLV)', value: 0.6 },
      { name: 'Vanilla Pudding (FLV)', value: 0.8 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 151048',
  },
  {
    id: 100017,
    name: 'Boss Reserve Clone (folkart)',
    flavors: [
      { name: 'Milk & Honey (FLV)', value: 1.5 },
      { name: 'Acetyl Pyrazine 5% (TPA)', value: 1 },
      { name: 'Biscuit (INW)', value: 0.25 },
      { name: 'Banana Cream (TPA)', value: 1.5 },
      { name: 'Super Sweet (CAP)', value: 0.25 },
    ],
    createdAt: '2026-01-19T00:00:00.000Z',
    source: 'e-liquid-recipes.com - Remix Month',
  },
  {
    id: 100018,
    name: 'Bronuts',
    flavors: [
      { name: 'Chocolate Glazed Doughnut (CAP)', value: 7 },
      { name: 'Joy (FA)', value: 0.75 },
      { name: 'Yellow Cake (FW)', value: 1 },
      { name: 'Biscuit (INW)', value: 0.75 },
    ],
    createdAt: '2026-01-05T00:00:00.000Z',
    source: 'e-liquid-recipes.com - enyawreklaw',
  },
  {
    id: 100019,
    name: 'Bust-a-Nut',
    flavors: [
      { name: 'Bavarian Cream (FW)', value: 3 },
      { name: 'Butter Pecan (FW)', value: 4 },
      { name: 'Hazelnut (FW)', value: 7 },
      { name: 'Sweet Cream (FW)', value: 5 },
      { name: 'Sweetener Sucralose (FW)', value: 1 },
    ],
    createdAt: '2026-02-09T00:00:00.000Z',
    source: 'craftvaping.com - Bust-a-Nut (alisa)',
  },
  {
    id: 100020,
    name: 'Caramel Apple',
    flavors: [
      { name: 'Double Apple (CAP)', value: 8 },
      { name: 'Sour (TPA)', value: 0.5 },
      { name: 'Caramel Candy (TPA)', value: 2 },
      { name: 'Cotton Candy (TPA)', value: 2 },
      { name: 'Green Apple (TPA)', value: 2 },
    ],
    createdAt: '2026-02-09T00:00:00.000Z',
    source: '99juices.com - recipe 2264',
  },
  {
    id: 100021,
    name: 'Caramel Butter Creme Brulee',
    flavors: [
      { name: 'Super Sweet (CAP)', value: 1 },
      { name: 'Vanilla Pudding (FLV)', value: 2 },
      { name: 'Custard Premium (FA)', value: 2 },
      { name: 'Creme Brulee (INW)', value: 1 },
      { name: 'Caramel Butter (WF)', value: 1.5 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: 'alltheflavors.com - Caramel Butter Creme Brulee',
  },
  {
    id: 100022,
    name: 'Castle Long Clone (Five Pawns)',
    flavors: [
      { name: 'Acetyl Pyrazine 5% (TPA)', value: 1.55 },
      { name: 'Red Oak (TPA)', value: 2.59 },
      { name: 'Bourbon Vanilla Bourbon (FA)', value: 2.07 },
      { name: 'Brown Sugar (TPA)', value: 2.59 },
      { name: 'Coconut Extra (TPA)', value: 5.18 },
      { name: 'Kentucky Bourbon (TPA)', value: 6.22 },
      { name: 'Toasted Almond (TPA)', value: 3.11 },
      { name: 'Vanillin 10 (TPA)', value: 1.04 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: '99juices.com - recipe 2248',
  },
  {
    id: 100023,
    name: 'Charlie Noble Commodore Pearry',
    flavors: [
      { name: 'Pear (TPA)', value: 6.5 },
      { name: 'Bavarian Cream (TPA)', value: 3.5 },
      { name: 'Vanilla Custard (TPA)', value: 3.5 },
      { name: 'French Vanilla (TPA)', value: 1.5 },
      { name: 'Coconut (TPA)', value: 1 },
      { name: 'Caramel (Original) (TPA)', value: 0.5 },
    ],
    createdAt: '2026-01-28T00:00:00.000Z',
    source: '99juices.com - recipe 4873',
  },
  {
    id: 100024,
    name: 'cinnamon rolls 1 (cloudking85)',
    flavors: [
      { name: 'Cinnamon Danish (TPA)', value: 5 },
      { name: 'Cinnamon Ceylon (FA)', value: 3 },
      { name: 'Cinnamon Sugar Cookie (TPA)', value: 3 },
      { name: 'DX Caramel Original (TPA)', value: 3 },
      { name: 'Brown Sugar (TPA)', value: 2.5 },
      { name: 'Ethyl Maltol (GEN)', value: 0.5 },
    ],
    createdAt: '2026-02-06T00:00:00.000Z',
    source: '99juices.com - recipe 10565',
  },
  {
    id: 100025,
    name: 'Cinnamon Toast Crunch',
    flavors: [
      { name: 'Marshmallow (TPA)', value: 0.89 },
      { name: 'Cinnamon Danish (TPA)', value: 6.25 },
      { name: 'Graham Cracker Clear (TPA)', value: 1.79 },
      { name: 'Whipped Cream (TPA)', value: 1.79 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 2490',
  },
  {
    id: 100026,
    name: 'Cloudy Lemonade',
    flavors: [
      { name: 'Cotton Candy 10% EM (TPA)', value: 1 },
      { name: 'Lemon Shisha (INW)', value: 6 },
      { name: 'Lemon Sicily (FA)', value: 1 },
      { name: 'Lemonade (FLV)', value: 3 },
      { name: 'Super Sweet (CAP)', value: 1 },
      { name: 'WS-23 30%', value: 3 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: 'craftvaping.com - Cloudy Lemonade',
  },
  {
    id: 100027,
    name: 'Coconut Cream Pie v1',
    flavors: [
      { name: 'Pie Crust (TPA)', value: 5 },
      { name: 'Toasted Marshmallow (TPA)', value: 2 },
      { name: 'Sweetener (TPA)', value: 0.5 },
      { name: 'Whipped Cream (TPA)', value: 2 },
      { name: 'Vanilla Custard (TPA)', value: 2 },
      { name: 'Coconut (CAP)', value: 15 },
      { name: 'Bavarian Cream (Vanilla) (LA)', value: 4 },
    ],
    createdAt: '2026-02-09T00:00:00.000Z',
    source: '99juices.com - recipe 968',
  },
  {
    id: 100028,
    name: 'Cosmic Fog Milk and Honey Clone',
    flavors: [
      { name: 'Graham Cracker (TPA)', value: 3 },
      { name: 'Marshmallow (TPA)', value: 1.8 },
      { name: 'Peanut Butter (TPA)', value: 0.9 },
      { name: 'Vanilla Custard (TPA)', value: 1.2 },
      { name: 'Vanilla Swirl (TPA)', value: 1.2 },
    ],
    createdAt: '2026-01-15T00:00:00.000Z',
    source: 'e-liquid-recipes.com - recipe 254455',
  },
  {
    id: 100029,
    name: 'Cosmic Ice',
    flavors: [
      { name: 'Wintergreen (TPA)', value: 2 },
      { name: 'Spearmint (TPA)', value: 0.2 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 236220',
  },
  {
    id: 100030,
    name: 'Cream Pop',
    flavors: [
      { name: 'Sweetener (TPA)', value: 4.37 },
      { name: 'Orange Cream (TPA)', value: 12 },
      { name: 'Vanilla Custard (TPA)', value: 2 },
      { name: 'Vanilla Swirl (TPA)', value: 3 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 1918',
  },
  {
    id: 100031,
    name: 'Creme Brulee Cheesecake',
    flavors: [
      { name: 'Creme Brulee (INW)', value: 2 },
      { name: 'Custard (INW)', value: 3 },
      { name: 'Shisha Vanilla (INW)', value: 1 },
      { name: 'Yes, We Cheesecake (INW)', value: 3 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 117476',
  },
  {
    id: 100032,
    name: 'Dragons Blood',
    flavors: [
      { name: 'Dragonfruit (TPA)', value: 5 },
      { name: 'Strawberry (Ripe) (TPA)', value: 10 },
      { name: 'Vanilla Swirl (TPA)', value: 3 },
      { name: 'Sweet Cream (TPA)', value: 5 },
      { name: 'Bavarian Cream (LA)', value: 2 },
      { name: 'Cotton Candy (TPA)', value: 2 },
    ],
    createdAt: '2026-01-21T00:00:00.000Z',
    source: '99juices.com - recipe 1360',
  },
  {
    id: 100033,
    name: 'Ella\'s Shortbread Biscuit',
    flavors: [
      { name: 'Acetyl Pyrazine 5% (TPA)', value: 0.5 },
      { name: 'Biscuit (INW)', value: 1.5 },
      { name: 'Sugar Cookie (CAP)', value: 4 },
      { name: 'Vanilla Custard v1 (CAP)', value: 2 },
      { name: 'Vanilla Shisha (INW)', value: 1 },
    ],
    createdAt: '2026-02-03T00:00:00.000Z',
    source: 'craftvaping.com - Ellas Shortbread Biscuit',
  },
  {
    id: 100034,
    name: 'Farley\'s Gnarly Sauce Clone (Bad Drip)',
    flavors: [
      { name: 'Bubble Gum (LA)', value: 5 },
      { name: 'Strawberry (TPA)', value: 7 },
      { name: 'Kiwi (FW)', value: 8 },
      { name: 'Ethyl Maltol (TPA)', value: 2 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: 'craftvaping.com - Farleys Gnarly Sauce',
  },
  {
    id: 100035,
    name: 'Fresh Squeeze Clone (Element)',
    flavors: [
      { name: 'Ecto Cooler (TPA)', value: 6 },
      { name: 'Sucralose (CAP)', value: 1.5 },
      { name: 'Sweet Tangerine (CAP)', value: 1.2 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: 'craftvaping.com - Fresh Squeeze Element',
  },
  {
    id: 100036,
    name: 'Fresh Watermelon',
    flavors: [
      { name: 'Watermelon (TPA)', value: 8 },
      { name: 'Koolada 10 PG (TPA)', value: 3 },
    ],
    createdAt: '2026-01-24T00:00:00.000Z',
    source: '99juices.com - recipe 5585',
  },
  {
    id: 100037,
    name: 'Fruit Loops cream',
    flavors: [
      { name: 'Fruit Circles (CAP)', value: 7 },
      { name: 'Bavarian Cream (FW)', value: 1.5 },
      { name: 'White Chocolate (FW)', value: 4 },
      { name: 'Vienna Cream (FA)', value: 2 },
    ],
    createdAt: '2026-01-30T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 247367',
  },
  {
    id: 100038,
    name: 'Glass Apple',
    flavors: [
      { name: 'Fuji Apple (FA)', value: 3 },
      { name: 'Koolada 10% (TPA)', value: 1.5 },
      { name: 'Peach (Juicy) (TPA)', value: 6 },
      { name: 'Strawberry (Ripe) (TPA)', value: 8 },
    ],
    createdAt: '2026-01-06T00:00:00.000Z',
    source: 'e-liquid-recipes.com - recipe 435001',
  },
  {
    id: 100039,
    name: 'God Milk',
    flavors: [
      { name: 'Strawberry (TPA)', value: 4 },
      { name: 'Strawberry (Ripe) (TPA)', value: 4 },
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 3 },
      { name: 'Bavarian Cream (TPA)', value: 3 },
      { name: 'Dragonfruit (TPA)', value: 1 },
    ],
    createdAt: '2026-01-04T00:00:00.000Z',
    source: 'e-liquid-recipes.com - SkiddlzNinja',
  },
  {
    id: 100040,
    name: 'Gordona Vapes Mr. Peanut Butter',
    flavors: [
      { name: 'Peanut Butter (TPA)', value: 7.5 },
      { name: 'Marshmallow (TPA)', value: 4 },
      { name: 'Vanilla Custard (TPA)', value: 4 },
      { name: 'Graham Cracker (TPA)', value: 2.5 },
      { name: 'Bavarian Cream (TPA)', value: 2.5 },
      { name: 'Vanilla Swirl (TPA)', value: 2 },
      { name: 'Coconut Candy (TPA)', value: 1.5 },
      { name: 'Caramel Original (TPA)', value: 1 },
    ],
    createdAt: '2026-02-09T00:00:00.000Z',
    source: '99juices.com - recipe 4874',
  },
  {
    id: 100041,
    name: 'Got Dang Betterest Fruity Loopy Loops',
    flavors: [
      { name: 'Cereal 27 (CAP)', value: 1.5 },
      { name: 'Fruit Circles (CAP)', value: 8 },
      { name: 'Super Sweet (CAP)', value: 1.25 },
      { name: 'Sweet Cream (CAP)', value: 1 },
      { name: 'Vienna Cream (FA)', value: 1.25 },
    ],
    createdAt: '2026-01-29T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 91914',
  },
  {
    id: 100042,
    name: 'Gourmet Vanilla Custard Deluxe for JimmyLee',
    flavors: [
      { name: 'Bavarian Cream (TPA)', value: 1.25 },
      { name: 'Butter Cream (CAP)', value: 1.5 },
      { name: 'Caramel (Original) (TPA)', value: 1 },
      { name: 'Cotton Candy (TPA)', value: 0.5 },
      { name: 'French Vanilla Deluxe (TPA)', value: 2 },
      { name: 'Toasted Almond (TPA)', value: 0.75 },
      { name: 'Vanilla Custard (CAP)', value: 5.5 },
      { name: 'Vanilla Ice Cream (LB)', value: 2.5 },
    ],
    createdAt: '2026-02-03T00:00:00.000Z',
    source: 'vceliquidrecipes.com - recipe 45268',
  },
  {
    id: 100043,
    name: 'Grack Juice (Philosaphucker)',
    flavors: [
      { name: 'Cactus (INW)', value: 2.25 },
      { name: 'Dragonfruit (TPA)', value: 1 },
      { name: 'Meringue (FA)', value: 1 },
      { name: 'Raspberry (INW)', value: 0.5 },
      { name: 'Sweet Strawberry (CAP)', value: 1.5 },
      { name: 'Grape (INW)', value: 4 },
      { name: 'Koolada 10% (TPA)', value: 0.75 },
    ],
    createdAt: '2026-01-16T00:00:00.000Z',
    source: 'craftvaping.com - Philosaphucker',
  },
  {
    id: 100044,
    name: 'Granola Bar Clone (Yogi E Liquid)',
    flavors: [
      { name: 'Apple Pie (TPA)', value: 9 },
      { name: 'Vanilla Bean Ice Cream (TPA)', value: 5 },
      { name: 'Caramel Candy (TPA)', value: 2.5 },
      { name: 'Cotton Candy 10% EM (TPA)', value: 1.5 },
      { name: 'Bavarian Cream (TPA)', value: 1 },
      { name: 'Graham Cracker (TPA)', value: 1 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: 'craftvaping.com - Granola Bar Yogi',
  },
  {
    id: 100045,
    name: 'Grants Vanilla Custard (my way)',
    flavors: [
      { name: 'French Vanilla (CAP)', value: 3 },
      { name: 'New York Cheesecake (CAP)', value: 3 },
      { name: 'Vanilla Custard (CAP)', value: 4 },
    ],
    createdAt: '2026-01-07T00:00:00.000Z',
    source: 'e-liquid-recipes.com - recipe 11224',
  },
  {
    id: 100046,
    name: 'Guava-Lime Candy',
    flavors: [
      { name: 'Cactus (INW)', value: 0.5 },
      { name: 'Dragon Fruit (INW)', value: 1 },
      { name: 'Fuji Apple (FA)', value: 0.25 },
      { name: 'Lemon Lime (CAP)', value: 4 },
      { name: 'Lime (INW)', value: 0.25 },
      { name: 'Pink Guava (FLV)', value: 0.25 },
    ],
    createdAt: '2026-01-30T00:00:00.000Z',
    source: 'craftvaping.com - Guava Lime Candy',
  },
  {
    id: 100047,
    name: 'Honey Pearry Clone',
    flavors: [
      { name: 'Honeydew (TPA)', value: 3 },
      { name: 'Strawberry (Ripe) (TPA)', value: 5 },
      { name: 'Pear (TPA)', value: 6 },
      { name: 'Apricot (TPA)', value: 3 },
    ],
    createdAt: '2026-01-13T00:00:00.000Z',
    source: '99juices.com',
  },
  {
    id: 100048,
    name: 'Its a Guava Thing',
    flavors: [
      { name: 'Sweet Guava (CAP)', value: 5 },
      { name: 'French Vanilla Icecream (HS)', value: 1.25 },
      { name: 'Yes, We Cheesecake (INW)', value: 1 },
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 1.5 },
      { name: 'Pudding Base (VT)', value: 0.75 },
    ],
    createdAt: '2026-01-30T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 132214',
  },
  {
    id: 100049,
    name: 'Key Lime Cookie Clone (Ripe Vapes)',
    flavors: [
      { name: 'Catalan Cream (FA)', value: 1 },
      { name: 'Cookie Biscotto (FA)', value: 1.5 },
      { name: 'Key Lime (TPA)', value: 3 },
      { name: 'Lime Cold Pressed (FA)', value: 1 },
      { name: 'Sugar Cookie (CAP)', value: 0.5 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: 'craftvaping.com - Key Lime Cookie Ripe Vapes',
  },
  {
    id: 100050,
    name: 'Lemon by the Pound (McFly)',
    flavors: [
      { name: 'Golden Butter (CAP)', value: 0.75 },
      { name: 'Butter Cream (FW)', value: 0.5 },
      { name: 'Meringue (FA)', value: 2 },
      { name: 'Lemon Juicy (JF)', value: 2 },
      { name: 'Yellow Cake (JF)', value: 4 },
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 0.5 },
    ],
    createdAt: '2026-02-06T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 21248',
  },
  {
    id: 100051,
    name: 'Lemon Tart Remix (Dinner Lady)',
    flavors: [
      { name: 'Bavarian Cream (TPA)', value: 1 },
      { name: 'Biscuit (INW)', value: 0.5 },
      { name: 'Custard (FA)', value: 1.5 },
      { name: 'Golden Butter (CAP)', value: 0.3 },
      { name: 'Graham Cracker Clear (TPA)', value: 2 },
      { name: 'Juicy Lemon (CAP)', value: 1 },
      { name: 'Lemon Meringue Pie (FW)', value: 3 },
      { name: 'Lemon Sicily (FA)', value: 3 },
      { name: 'Meringue (FA)', value: 1.5 },
      { name: 'Sweetener (TPA)', value: 0.75 },
    ],
    createdAt: '2026-02-05T00:00:00.000Z',
    source: 'craftvaping.com - Lemon Tart Remix Dinner Lady',
  },
  {
    id: 100052,
    name: 'Looper Clone (ANML)',
    flavors: [
      { name: 'Fruit Circles (TPA)', value: 8 },
      { name: 'Sweetener (TPA)', value: 1 },
      { name: 'Vanilla Custard (CAP)', value: 1 },
      { name: 'Bavarian Cream (TPA)', value: 4 },
      { name: 'Berry Cereal (TPA)', value: 6 },
      { name: 'Marshmallow (TPA)', value: 4 },
      { name: 'Sweet Cream (TPA)', value: 2 },
      { name: 'Vanilla Swirl (TPA)', value: 2 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 2595',
  },
  {
    id: 100053,
    name: 'Mango Brulee',
    flavors: [
      { name: 'Mango (FE)', value: 4 },
      { name: 'Creme Brulee (INW)', value: 2 },
      { name: 'Custard (INW)', value: 3 },
      { name: 'Shisha Vanilla (INW)', value: 1 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 141838',
  },
  {
    id: 100054,
    name: 'Mango Dragon',
    flavors: [
      { name: 'Dragonfruit (TPA)', value: 5 },
      { name: 'Mango (TPA)', value: 10 },
      { name: 'Vanilla Swirl (TPA)', value: 3 },
      { name: 'Sweet Cream (TPA)', value: 5 },
      { name: 'Bavarian Cream Vanilla (LA)', value: 2 },
      { name: 'Sweetener (TPA)', value: 2 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 213',
  },
  {
    id: 100055,
    name: 'Marshmallow Man by Donuts Ejuice',
    flavors: [
      { name: 'Acetyl Pyrazine 5% (TPA)', value: 0.33 },
      { name: 'Bavarian Cream (TPA)', value: 1.1 },
      { name: 'Cake Batter (CAP)', value: 0.59 },
      { name: 'Marshmallow (FA)', value: 3.42 },
      { name: 'Marshmallow (TPA)', value: 3.42 },
      { name: 'Strawberry (Ripe) (TPA)', value: 0.85 },
      { name: 'Sugar Cookie (CAP)', value: 2.1 },
      { name: 'Sweet Cream (TPA)', value: 2 },
      { name: 'Sweetener (Sucralose) (TPA)', value: 4 },
      { name: 'Vanilla Bean Ice Cream (FW)', value: 2 },
    ],
    createdAt: '2026-02-04T00:00:00.000Z',
    source: 'craftvaping.com - Marshmallow Man Donuts',
  },
  {
    id: 100056,
    name: 'Masala Chai',
    flavors: [
      { name: 'Chai Spice (FLV)', value: 0.75 },
      { name: 'Ginger (FLV)', value: 0.25 },
      { name: 'Heat (FLV)', value: 0.1 },
      { name: 'Sweetener (FW)', value: 0.5 },
      { name: 'Cream Milky Undertone PG (OOO)', value: 2 },
      { name: 'Black Tea (SC)', value: 1.5 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 222155',
  },
  {
    id: 100057,
    name: 'Monster Melon Clone (Cuttwood)',
    flavors: [
      { name: 'Cantaloupe (TPA)', value: 5 },
      { name: 'Mango (TPA)', value: 5 },
      { name: 'Papaya (TPA)', value: 5 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: 'craftvaping.com - Monster Melon Cuttwood',
  },
  {
    id: 100058,
    name: 'Moose Milk (Original)',
    flavors: [
      { name: 'Bavarian Cream (DX) (TPA)', value: 2.5 },
      { name: 'Butter Pecan (FW)', value: 3.5 },
      { name: 'Caramel Candy (FW)', value: 3.5 },
      { name: 'Coconut Extra (TPA)', value: 0.5 },
      { name: 'Salted Caramel (OOO)', value: 2 },
      { name: 'Sweet Cream (FW)', value: 2 },
      { name: 'Toasted Almond (TPA)', value: 2 },
      { name: 'Vienna Cream (FA)', value: 2 },
    ],
    createdAt: '2026-01-08T00:00:00.000Z',
    source: 'e-liquid-recipes.com - recipe 1938417',
  },
  {
    id: 100059,
    name: 'Mother\'s Unicorn Milk',
    flavors: [
      { name: 'Bavarian Cream (TPA)', value: 4 },
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 5 },
      { name: 'Strawberry (Ripe) (TPA)', value: 10 },
      { name: 'Sweet Cream (TPA)', value: 4 },
      { name: 'Vanilla Custard (TPA)', value: 3 },
    ],
    createdAt: '2026-01-03T00:00:00.000Z',
    source: 'e-liquid-recipes.com',
  },
  {
    id: 100060,
    name: 'Mothers Milk Clone',
    flavors: [
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 5 },
      { name: 'Strawberry (Ripe) (TPA)', value: 10 },
      { name: 'Sweet Cream (TPA)', value: 3 },
      { name: 'Bavarian Cream (TPA)', value: 3 },
      { name: 'Vanilla Custard (TPA)', value: 2 },
    ],
    createdAt: '2026-01-25T00:00:00.000Z',
    source: '99juices.com - recipe 28',
  },
  {
    id: 100061,
    name: 'Muffin Man by One Hit Wonder (Mk-2)',
    flavors: [
      { name: 'Apple Pie (CAP)', value: 2 },
      { name: 'Cake (Yellow) (FW)', value: 0.5 },
      { name: 'Cinnamon Danish Swirl (CAP)', value: 4.4 },
      { name: 'Double Apple (CAP)', value: 5 },
      { name: 'Marshmallow (CAP)', value: 0.5 },
      { name: 'Sweetener (Sucralose) (TPA)', value: 0.5 },
    ],
    createdAt: '2026-02-04T00:00:00.000Z',
    source: 'craftvaping.com - Muffin Man One Hit Wonder',
  },
  {
    id: 100062,
    name: 'Mustard Milk',
    flavors: [
      { name: 'Strawberry (TPA)', value: 6 },
      { name: 'Vanilla Bean Ice Cream (TPA)', value: 8 },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
    source: 'e-liquid-recipes.com - fizzmustard',
  },
  {
    id: 100063,
    name: 'Nana Cream Clone',
    flavors: [
      { name: 'Banana Cream (LA)', value: 5 },
      { name: 'Dragonfruit (TPA)', value: 3 },
      { name: 'Strawberry (TPA)', value: 7 },
    ],
    createdAt: '2026-01-02T00:00:00.000Z',
    source: 'e-liquid-recipes.com - fizzmustard',
  },
  {
    id: 100064,
    name: 'Orange Creamsicle',
    flavors: [
      { name: 'Orange Cream (TPA)', value: 9 },
      { name: 'Vanilla Swirl (TPA)', value: 4 },
      { name: 'Cotton Candy (TPA)', value: 2 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: '99juices.com - recipe 855',
  },
  {
    id: 100065,
    name: 'Peanut Butter Milkshake',
    flavors: [
      { name: 'Peanut Butter (TPA)', value: 2.5 },
      { name: 'Sweet Cream (TPA)', value: 3 },
      { name: 'Vanilla Custard (CAP)', value: 1.5 },
      { name: 'Carmel Caramel (FA)', value: 1 },
      { name: 'Super Sweet (CAP)', value: 0.75 },
    ],
    createdAt: '2026-02-09T00:00:00.000Z',
    source: 'alltheflavors.com - Peanut Butter Milkshake',
  },
  {
    id: 100066,
    name: 'Pink Lemonade Clone (Element)',
    flavors: [
      { name: 'Key Lime (TPA)', value: 1.5 },
      { name: 'Lemonade (FLV)', value: 4 },
      { name: 'Lime Tahity Cold Pressed (FA)', value: 2 },
      { name: 'Marshmallow (FA)', value: 1 },
      { name: 'Super Sweet (CAP)', value: 1 },
      { name: 'Sweet Strawberry (CAP)', value: 2 },
      { name: 'Sweet Tangerine (CAP)', value: 2 },
      { name: 'Vanilla Swirl (TPA)', value: 1 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: 'craftvaping.com - Pink Lemonade Element',
  },
  {
    id: 100067,
    name: 'Queenside Clone (Five Pawns)',
    flavors: [
      { name: 'Blood Orange (FW)', value: 4 },
      { name: 'French Vanilla (CAP)', value: 3 },
      { name: 'Orange Cream (TPA)', value: 3 },
      { name: 'Vanilla Custard v1 (CAP)', value: 10 },
      { name: 'Vanillin 10% (TPA)', value: 0.2 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: 'craftvaping.com - Queenside Five Pawns',
  },
  {
    id: 100068,
    name: 'Raspberry Custard (Coop34)',
    flavors: [
      { name: 'Apple Pie (FA)', value: 2 },
      { name: 'Cream Fresh (FA)', value: 1 },
      { name: 'Meringue (FA)', value: 1 },
      { name: 'Raspberry (INW)', value: 1 },
      { name: 'Raspberry (Sweet) (TPA)', value: 2 },
      { name: 'Vanilla Custard (CAP)', value: 1 },
    ],
    createdAt: '2026-02-03T00:00:00.000Z',
    source: 'craftvaping.com - Raspberry Custard Coop34',
  },
  {
    id: 100069,
    name: 'Reloaded Donuts (VaporAlchemist)',
    flavors: [
      { name: 'Almond (FA)', value: 0.6 },
      { name: 'Butterscotch (FW)', value: 1.8 },
      { name: 'Cake Batter Dip (FW)', value: 2.5 },
      { name: 'Cinnamon Danish Swirl (CAP)', value: 0.6 },
      { name: 'Glazed Doughnut (CAP)', value: 3 },
      { name: 'Honey (FA)', value: 0.2 },
      { name: 'Joy (FA)', value: 0.35 },
      { name: 'Sugar Cookie (CAP)', value: 4 },
      { name: 'Sweetener (Sucralose) (TPA)', value: 1.6 },
      { name: 'Vanilla Custard v1 (CAP)', value: 2 },
      { name: 'Vanillin 10% (TPA)', value: 0.15 },
    ],
    createdAt: '2026-02-04T00:00:00.000Z',
    source: 'craftvaping.com - Reloaded Donuts VaporAlchemist',
  },
  {
    id: 100070,
    name: 'Ripe Dragon Cream',
    flavors: [
      { name: 'Bavarian Cream (TPA)', value: 6 },
      { name: 'Dragonfruit (TPA)', value: 10 },
      { name: 'Cotton Candy (TPA)', value: 1 },
      { name: 'Strawberry (Ripe) (TPA)', value: 4 },
    ],
    createdAt: '2026-01-20T00:00:00.000Z',
    source: '99juices.com - recipe 2477',
  },
  {
    id: 100071,
    name: 'Round Fruit Cereal',
    flavors: [
      { name: 'Milk & Honey (FLV)', value: 1 },
      { name: 'Fruit Rings (FW)', value: 4 },
      { name: 'Cream Fresh (FA)', value: 1 },
      { name: 'Meringue (FA)', value: 0.5 },
      { name: 'Bavarian Cream (TPA)', value: 3 },
      { name: 'Marshmallow (TPA)', value: 1 },
      { name: 'Vanilla Swirl (TPA)', value: 3 },
    ],
    createdAt: '2026-01-29T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 15782',
  },
  {
    id: 100072,
    name: 'RY4',
    flavors: [
      { name: 'French Vanilla (TPA)', value: 6 },
      { name: 'Caramel Original (TPA)', value: 9 },
      { name: 'Sweetener (TPA)', value: 3 },
      { name: 'RY4 Double (TPA)', value: 4 },
      { name: 'Brown Sugar (TPA)', value: 5 },
      { name: 'Bavarian Cream (LA)', value: 6 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: '99juices.com - recipe 1102',
  },
  {
    id: 100073,
    name: 'Shire Sour Gummy Bear',
    flavors: [
      { name: 'Gummy Candy (TPA)', value: 3 },
      { name: 'Strawberry (TPA)', value: 3 },
      { name: 'Raspberry (TPA)', value: 3 },
      { name: 'Lemon (water soluble) (TPA)', value: 2 },
      { name: 'Key Lime (FW)', value: 2 },
      { name: 'Orange Mandarin (TPA)', value: 2 },
      { name: 'Sour (TPA)', value: 2 },
      { name: 'Sweetener (TPA)', value: 2 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 5224',
  },
  {
    id: 100074,
    name: 'Shurb Clone (Jimmy The Juice Man)',
    flavors: [
      { name: 'Cotton Candy EM (TPA)', value: 3.5 },
      { name: 'Beetle Juice (FW)', value: 6 },
      { name: 'Mandarin (FA)', value: 6.5 },
      { name: 'Key Lime (TPA)', value: 1.5 },
      { name: 'Whipped Cream (TPA)', value: 2.5 },
      { name: 'Vanilla Swirl (TPA)', value: 2.5 },
      { name: 'Raspberry (FA)', value: 5 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: 'craftvaping.com - Shurb Jimmy Juice Man',
  },
  {
    id: 100075,
    name: 'Simple Lemon Cake',
    flavors: [
      { name: 'Golden Butter (CAP)', value: 2 },
      { name: 'Cookie (FA)', value: 1.2 },
      { name: 'Lemon Sicily (FA)', value: 3.8 },
      { name: 'Lemon Cake (INW)', value: 1.5 },
    ],
    createdAt: '2026-02-06T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 15888',
  },
  {
    id: 100076,
    name: 'Simple Sugar Cookie (ID10-T)',
    flavors: [
      { name: 'Sugar Cookie (CAP)', value: 8 },
      { name: 'Vanilla Custard (CAP)', value: 4 },
    ],
    createdAt: '2026-01-12T00:00:00.000Z',
    source: 'dot1ml.com - ID10-T',
  },
  {
    id: 100077,
    name: 'Smoking Snake',
    flavors: [
      { name: 'Bavarian Cream (TPA)', value: 5.05 },
      { name: 'Honeydew (TPA)', value: 2.02 },
      { name: 'Pear (TPA)', value: 7.07 },
      { name: 'RY4 Double (TPA)', value: 2.02 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 22',
  },
  {
    id: 100078,
    name: 'Snake Oil Clone',
    flavors: [
      { name: 'Pear (TPA)', value: 11 },
      { name: 'Bavarian Cream (TPA)', value: 7 },
      { name: 'Coconut Extra (TPA)', value: 2 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 16',
  },
  {
    id: 100079,
    name: 'Snickerdoodle Custard',
    flavors: [
      { name: 'Cinnamon Danish Swirl (CAP)', value: 2.5 },
      { name: 'Sugar Cookie (CAP)', value: 6 },
      { name: 'Vanilla Custard (CAP)', value: 3 },
    ],
    createdAt: '2026-01-10T00:00:00.000Z',
    source: 'alltheflavors.com - CenCalVape',
  },
  {
    id: 100080,
    name: 'Snowy Fuji',
    flavors: [
      { name: 'Bavarian Cream (TPA)', value: 4 },
      { name: 'Caramel (CAP)', value: 4.5 },
      { name: 'Fuji Apple (FA)', value: 4.5 },
    ],
    createdAt: '2026-01-09T00:00:00.000Z',
    source: 'e-liquid-recipes.com',
  },
  {
    id: 100081,
    name: 'Spicy Sweet Chai Tea',
    flavors: [
      { name: 'Sweetener (TPA)', value: 3 },
      { name: 'Honey (TPA)', value: 2 },
      { name: 'Cinnamon Spice (TPA)', value: 6 },
      { name: 'Chai Tea (TPA)', value: 12 },
    ],
    createdAt: '2026-02-09T00:00:00.000Z',
    source: '99juices.com - recipe 15468',
  },
  {
    id: 100082,
    name: 'Strawberry Banana Milkshake',
    flavors: [
      { name: 'Banana Cream (TPA)', value: 4 },
      { name: 'Bavarian Cream (TPA)', value: 2 },
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 2 },
      { name: 'Strawberry (TPA)', value: 4 },
      { name: 'Strawberry (Ripe) (TPA)', value: 4 },
      { name: 'Sweet Cream (TPA)', value: 1 },
      { name: 'Vanilla Custard (TPA)', value: 1 },
      { name: 'Vanilla Swirl (TPA)', value: 1 },
      { name: 'Whipped Cream (TPA)', value: 1 },
    ],
    createdAt: '2026-02-01T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 17479',
  },
  {
    id: 100083,
    name: 'Strawberry Cheesecake (davidtime)',
    flavors: [
      { name: 'New York Cheesecake (CAP)', value: 10 },
      { name: 'Strawberry (Ripe) (TPA)', value: 8 },
    ],
    createdAt: '2026-02-02T00:00:00.000Z',
    source: '99juices.com - recipe 1820',
  },
  {
    id: 100084,
    name: 'Strawberry Cheesecake (jache)',
    flavors: [
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 6 },
      { name: 'Sweet Strawberry (CAP)', value: 10 },
      { name: 'Strawberries and Cream (TPA)', value: 2 },
    ],
    createdAt: '2026-02-02T00:00:00.000Z',
    source: '99juices.com - recipe 3270',
  },
  {
    id: 100085,
    name: 'Strawberry Cheesecake (mrowland)',
    flavors: [
      { name: 'Strawberry (Ripe) (TPA)', value: 10 },
      { name: 'Cheesecake (Graham Crust) (TPA)', value: 6 },
    ],
    createdAt: '2026-02-02T00:00:00.000Z',
    source: '99juices.com - recipe 6214',
  },
  {
    id: 100086,
    name: 'Strawberry Cloud Rat',
    flavors: [
      { name: 'French Vanilla (TPA)', value: 2 },
      { name: 'Bavarian Cream (TPA)', value: 6 },
      { name: 'Strawberry (TPA)', value: 6 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 1923',
  },
  {
    id: 100087,
    name: 'StrawBerry CoCoCaBana',
    flavors: [
      { name: 'Cheesecake Graham Crust (TPA)', value: 1 },
      { name: 'Sweet Strawberry (CAP)', value: 4 },
      { name: 'Coconut Extra (TPA)', value: 1.33 },
      { name: 'Marshmallow (TPA)', value: 2 },
      { name: 'Sweet Cream (TPA)', value: 1.67 },
      { name: 'Vanilla Custard (TPA)', value: 2.67 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 3543',
  },
  {
    id: 100088,
    name: 'Strawberry Island Cheesecake',
    flavors: [
      { name: 'Cheesecake Graham Crust (TPA)', value: 10.87 },
      { name: 'Strawberry Ripe (TPA)', value: 7.61 },
      { name: 'Sweet Cream (TPA)', value: 5.43 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 2371',
  },
  {
    id: 100089,
    name: 'Strawberry Kiwi',
    flavors: [
      { name: 'Strawberry (Ripe) (TPA)', value: 10 },
      { name: 'Kiwi (FW)', value: 5 },
      { name: 'Super Sweet (CAP)', value: 0.5 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: '99juices.com - recipe 4216',
  },
  {
    id: 100090,
    name: 'Strawnana Custard (Grubby)',
    flavors: [
      { name: 'Banana Cream (LA)', value: 4 },
      { name: 'Strawberry (Ripe) (TPA)', value: 4 },
      { name: 'Sweet Strawberry (CAP)', value: 3 },
      { name: 'Vanilla Custard (CAP)', value: 10 },
    ],
    createdAt: '2026-01-14T00:00:00.000Z',
    source: 'vceliquidrecipes.com - Grubby',
  },
  {
    id: 100091,
    name: 'Strawvana Cream Pie',
    flavors: [
      { name: 'Cheesecake Graham Crust (TPA)', value: 2 },
      { name: 'Strawberry Ripe (TPA)', value: 8 },
      { name: 'Banana Cream (LA)', value: 4 },
      { name: 'Bavarian Cream (TPA)', value: 2 },
      { name: 'Vanilla Custard (TPA)', value: 4 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 1872',
  },
  {
    id: 100092,
    name: 'Sucker Punch Clone (Suicide Bunny)',
    flavors: [
      { name: 'Bavarian Cream (TPA)', value: 2 },
      { name: 'Dragonfruit (TPA)', value: 14 },
      { name: 'Vanilla Swirl (TPA)', value: 4 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: 'craftvaping.com - Sucker Punch Suicide Bunny',
  },
  {
    id: 100093,
    name: 'Sugar Bear Clone (Cuttwood)',
    flavors: [
      { name: 'Cinnamon Roll (FW)', value: 6.9 },
      { name: 'Sugar Cookie v2 (CAP)', value: 2.8 },
      { name: 'Cinnamon Danish Swirl (CAP)', value: 4.1 },
    ],
    createdAt: '2026-01-18T00:00:00.000Z',
    source: '99juices.com - recipe 2643',
  },
  {
    id: 100094,
    name: 'Suicide Bunny The O.B.',
    flavors: [
      { name: 'Cheesecake Graham Crust (TPA)', value: 3 },
      { name: 'Caramel (TPA)', value: 0.5 },
      { name: 'Sweet Cream (TPA)', value: 4 },
      { name: 'Vanilla Custard (TPA)', value: 5 },
      { name: 'French Vanilla (TPA)', value: 2 },
      { name: 'Dulce de Leche (TPA)', value: 1 },
      { name: 'Bavarian Cream (TPA)', value: 4 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 3132',
  },
  {
    id: 100095,
    name: 'Sweet Shack Strawberry Watermelon Clone',
    flavors: [
      { name: 'Strawberry (TPA)', value: 12 },
      { name: 'Watermelon Candy (TPA)', value: 8 },
    ],
    createdAt: '2026-01-25T00:00:00.000Z',
    source: '99juices.com - recipe 3246',
  },
  {
    id: 100096,
    name: 'Tfa Tiramisu',
    flavors: [
      { name: 'Bavarian Cream (TPA)', value: 4 },
      { name: 'Double Chocolate (Dark) (TPA)', value: 2 },
      { name: 'French Vanilla Deluxe (TPA)', value: 2 },
      { name: 'Sweetener (TPA)', value: 2 },
      { name: 'Tiramisu (TPA)', value: 5 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: '99juices.com - recipe 2737',
  },
  {
    id: 100097,
    name: 'TGC\'s RY4 ADV',
    flavors: [
      { name: 'Bavarian Cream (TPA)', value: 4 },
      { name: 'Caramel Candy (TPA)', value: 4 },
      { name: 'RY4 Double (TPA)', value: 8 },
    ],
    createdAt: '2026-02-08T00:00:00.000Z',
    source: '99juices.com - recipe 12819',
  },
  {
    id: 100098,
    name: 'Tropical Tryst',
    flavors: [
      { name: 'Artificial Sweetener (Sucralose) (FW)', value: 0.5 },
      { name: 'Banana Custard (VT)', value: 1.5 },
      { name: 'Coconut (FLV)', value: 0.25 },
      { name: 'Cream (FLV)', value: 0.75 },
      { name: 'Juicy Strawberry (FA)', value: 1.5 },
      { name: 'Mango (FLV)', value: 1.5 },
      { name: 'Pink Guava (FLV)', value: 0.75 },
      { name: 'Strawberry (Red Touch) (FA)', value: 1.5 },
      { name: 'Sweet Coconut (FLV)', value: 1.25 },
    ],
    createdAt: '2026-01-31T00:00:00.000Z',
    source: 'vceliquidrecipes.com - recipe 2268',
  },
  {
    id: 100099,
    name: 'Unicorn Milk Clone (Cuttwood)',
    flavors: [
      { name: 'Butter Cream (CAP)', value: 1.5 },
      { name: 'Graham Cracker v1 (CAP)', value: 0.5 },
      { name: 'New York Cheesecake (CAP)', value: 0.5 },
      { name: 'Sweet Cream (CAP)', value: 1.5 },
      { name: 'Sweet Strawberry (CAP)', value: 8.5 },
      { name: 'Vanilla Bean Ice Cream (CAP)', value: 1 },
      { name: 'Vanilla Custard v1 (CAP)', value: 3 },
    ],
    createdAt: '2026-01-11T00:00:00.000Z',
    source: 'craftvaping.com - cuttwoodspy',
  },
  {
    id: 100100,
    name: 'Watermelon Candy',
    flavors: [
      { name: 'Super Sweet (CAP)', value: 1 },
      { name: 'Watermelon Candy (TPA)', value: 5 },
      { name: 'Double Watermelon (CAP)', value: 1.5 },
    ],
    createdAt: '2026-01-24T00:00:00.000Z',
    source: '99juices.com - recipe 9539',
  },
  {
    id: 100101,
    name: 'Watermelon Crack Clone (BX Vapor)',
    flavors: [
      { name: 'Watermelon (TPA)', value: 9.5 },
      { name: 'Jungle Juice (FW)', value: 4.5 },
      { name: 'Hard Candy (FW)', value: 3 },
      { name: 'Cool Mint (CAP)', value: 0.25 },
      { name: 'Koolada 10% (TPA)', value: 1.5 },
    ],
    createdAt: '2026-01-17T00:00:00.000Z',
    source: 'e-liquid-recipes.com - recipe 3759606',
  },
  {
    id: 100102,
    name: 'Watermelon Crack Redux',
    flavors: [
      { name: 'Watermelon Candy (TPA)', value: 0.5 },
      { name: 'Watermelon (TPA)', value: 9 },
      { name: 'Marshmallow (LA)', value: 1 },
      { name: 'Jungle Juice (FW)', value: 1.5 },
      { name: 'Hard Candy (FW)', value: 4 },
    ],
    createdAt: '2026-01-23T00:00:00.000Z',
    source: '99juices.com - recipe 17524',
  },
  {
    id: 100103,
    name: 'Watermelon Rancher',
    flavors: [
      { name: 'Hard Candy (FW)', value: 0.54 },
      { name: 'Candy Watermelon (FW)', value: 3.26 },
      { name: 'Sweet Watermelon (CAP)', value: 5.43 },
      { name: 'Watermelon Candy (TPA)', value: 3.26 },
    ],
    createdAt: '2026-01-26T00:00:00.000Z',
    source: '99juices.com - recipe 2202',
  },
  {
    id: 100104,
    name: 'Whipped Bluenilla Muffin',
    flavors: [
      { name: 'Blueberry Jam (CAP)', value: 1.2 },
      { name: 'Vanilla Whipped Cream (CAP)', value: 1.8 },
      { name: 'Blueberry Muffin (FLV)', value: 3 },
      { name: 'Vanilla Pudding (FLV)', value: 1.5 },
      { name: 'Blueberry (FW)', value: 1 },
      { name: 'Sweetener (FW)', value: 0.5 },
    ],
    createdAt: '2026-02-10T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 213770',
  },
  {
    id: 100105,
    name: 'Winter Mint',
    flavors: [
      { name: 'Wintergreen (TPA)', value: 2 },
      { name: 'Spearmint (TPA)', value: 1 },
      { name: 'Whipped Cream (TPA)', value: 3 },
      { name: 'Peppermint (CAP)', value: 5 },
      { name: 'Menthol Liquid 10% PG (WL)', value: 5 },
    ],
    createdAt: '2026-02-07T00:00:00.000Z',
    source: '99juices.com - recipe 263',
  },
  {
    id: 100106,
    name: 'Yummya Guava',
    flavors: [
      { name: 'Raspberry (CAP)', value: 2 },
      { name: 'Super Sweet (CAP)', value: 1.5 },
      { name: 'Apple Fuji (FA)', value: 0.5 },
      { name: 'Lime Tahity Cold Pressed (FA)', value: 0.5 },
      { name: 'Goyave (SA)', value: 6 },
      { name: 'WS-3 (Koolada) (SA)', value: 3 },
    ],
    createdAt: '2026-01-31T00:00:00.000Z',
    source: 'alltheflavors.com - recipe 39950',
  }
]
